### ISSUE TITLE
Replace OptionParser use with ArgumentParser

### ISSUE THREAD

**Issue by morenoh149** [viewflow/django-fsm#188]
Running the `graph_transitions` command currently throws ` RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead`

I think it's due to the use of `optparse` @ https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/management/commands/graph_transitions.py#L3

If this is correct we can replace it's usage with `argparse`.

**Comment by kmmbvnr** [comment]
Look it was implemented at some moment of time
