### ISSUE TITLE
Question: FSMKeyField

### ISSUE THREAD

**Issue by biggosh** [viewflow/django-fsm#199]
Hi,

I've create the model with the list of all allowed states and I put a FSMKeyField in the model where I need the FSM.

I understood that in the "state" field only values in the lookup table are allowed in the model with key. This not happens: I wrote something wrong or this is "by design"?

I've attached the models.py

Thanks in advance
BG
[models.zip](https://github.com/kmmbvnr/django-fsm/files/1576152/models.zip)

**Comment by kmmbvnr** [comment]
I'm not sure can FSMKeyField would ever works properly with current django-fsm implementation

I think the best way is to separate fsm and model as in the viewflow.fsm https://docs.viewflow.io/fsm/models.html

That solves the issue but not steeping into the problem at all
