### ISSUE TITLE
Support python enum as state value

### ISSUE THREAD

**Issue by Bartvds** [viewflow/django-fsm#204]
It would be cool if we could use python `enum` instances for the state values.

It kinda works for string enum's but using an `IntEnum` gives some weird errors.

**Comment by kmmbvnr** [comment]
There is a project that uses enum with django-fsm integer field

https://github.com/kogan/django-subscriptions/blob/master/src/subscriptions/states.py

https://github.com/kogan/django-subscriptions/tree/master/src/subscriptions

**Comment by shulcsm** [comment]
What about non-int enums with something like django-enumfields?

**Comment by kmmbvnr** [comment]
Implemented in the `viewflow.fsm` package - https://docs-next.viewflow.io/fsm/models.html
