### ISSUE TITLE
Question: Multi-table inheritance and different transitions

### ISSUE THREAD

**Issue by stefanfoulis** [viewflow/django-fsm#205]
I have a model with multi-table-inheritance. I'd like to put the state field on the shared model and have some "standard" transitions on there. On the subclasses of that model, there may be additional transitions that are specific to that subclass. And subclasses may do slightly different things for transitions with the same name.

Problem is that if I use a shared state field, all the transitions of all the subclasses end up being available to all instances.

My current workaround is to put the state field on the subclass and re-define all the common transitions.

Is there a better way to handle this?

**Comment by kmmbvnr** [comment]
First-class inheritance support was added to viewflow.fsm  https://docs.viewflow.io/fsm/inheritance.html
