### ISSUE TITLE
Question: Dynamic Targets fail due to unused method parameters

### ISSUE THREAD

**Issue by saranshbansal** [viewflow/django-fsm#206]
> target
target state parameter could point to a specific state or django_fsm.State implementation

```
@transition(
    field=state,
    source='for_moderators',
    target=GET_STATE(
        lambda self, allowed: 'published' if allowed else 'rejected',
        states=['published', 'rejected']))
def moderate(self, allowed):
    self.allowed=allowed
```

I'm using the above approach to resolve dynamic target states. My function looks like this:
```

    @fsm_log_by
    @transition(
        field=state,
        source=[constants.BookingState.on_hold],
        target=GET_STATE(
            lambda self: constants.BookingState.camop_assigned if self.camera_operator else constants.BookingState.active,
            states=[constants.BookingState.active, constants.BookingState.camop_assigned]),
        permission=can_make_active,
    )
    def make_active(self, by=None):
        async('some async task', self.pk)
        async('some other async task', self.pk)

```
I have an additional `by=None` which is used for logging purposes. However, when I run this function, it says:
`
<lambda>() got an unexpected keyword argument 'by'
`

I don't understand why lambda is considering the parameter which I have not even declared in the lambda. I can run it if i remove `by=None` from the make_active function but I cannot do that as it is an important parameter.

Please help.

**Comment by kmmbvnr** [comment]
Closing since lack of resource on this project
