### ISSUE TITLE
Allow transitions from another class

### ISSUE THREAD

**Issue by shepsels** [viewflow/django-fsm#207]
I would like the transition function be responsible for all the "side effect" of the transition.
When implementing, the transition function should make some process which should not be written in the model class, but also involve some persistency. 
I can't call from models module a method from another class which will eventually use models again since I'm getting a circular dependency.
Does it make sense to implement the transition function in another class? Is that possible?

Thanks

**Comment by aimestereo** [comment]
I'm totally agree

**Comment by kmmbvnr** [comment]
Yep, the new viewflow.fsm separate model and fsm models to avoid such kind of problems https://docs.viewflow.io/fsm/inheritance.html
