### ISSUE TITLE
Unsupported lookup 'in' for FSMField or join on the field not permitted.

### ISSUE THREAD

**Issue by snyaggarwal** [viewflow/django-fsm#208]
Given `status` is an FSMField, querying this: `status__in': ['planned', 'confirmed']`, raises, `Unsupported lookup 'in' for FSMField or join on the field not permitted.`

WHY? Any workaround?

**Comment by peterfarrell** [comment]
We'd need some more example to see what you are seeing.  I've tried where the `state` field is a FSMField():

```
>> pp = MyObject.objects.filter(state__in=['Waiting', 'Completed'])
>> pp
<QuerySet [... results ...]>
```

Are you potentially using the FSMKeyField? That is a FK lookup so your filter would be a bit different:

https://github.com/viewflow/django-fsm#foreign-key-constraints-support

Using the example code from the link above, you have to filter into the FK relation:

```
posts = BlogPost.object.filter(state__label__in=['_NEW_', '_PUBLISHED_'])
```

Hope this helps.
