### ISSUE TITLE
Cannot use transition methods from proxy models

### ISSUE THREAD

**Issue by rvinzent** [viewflow/django-fsm#209]
I would like to define my transition methods on the proxy models instead of the base model.

    class BaseModel(models.Model):
        class State:
            FIRST = 'first'
            SECOND = 'second'
         
        STATE_CHOICES = (
            (State.FIRST, 'first', 'FirstModel'),
            (State.SECOND, 'second', 'SecondModel')
        )
        state = FSMField(
            state_choices=STATE_CHOICES,
            default=State.FIRST,
            protected=True)
    
    class FirstModel(BaseModel):
        class Meta:
            proxy = True
        
        @transition(
            field=BaseModel.state,
            source=BaseModel.State.FIRST,
            target=BaseModel.State.SECOND)
        def proceed(self):
            pass

    class SecondModel(BaseModel):
        class Meta:
            proxy = True

Currently this throws the following exception`:

    Traceback: 
        first_model_instance.proceed()
        File "path/to/django_fsm/__init__.py", line 515, in _change_state
            return fsm_meta.field.change_state(instance, func, *args, **kwargs)
        AttributeError: 'FSMFieldDescriptor' object has no attribute 'change_state'

Django version `2.1`
Possibly related to #207

**Comment by kmmbvnr** [comment]
You can't just reference fields as Model.fieldname, use `fieldname` strings

**Comment by levinotik** [comment]
I ran into a similar problem. Can you elaborate on what you mean by `fieldname` strings? 

If I just do `@transition(field='bla'...)` that fails with 

> AttributeError: 'str' object has no attribute 'change_state'

What's the right way to reference the fields? 

Thank you!

**Comment by ntouran** [comment]
@kmmbvnr I also don't understand the suggestion. Can you give an example decorator?

**Comment by glowang** [comment]
Same as @levinotik, I used the exact same line as @ntouran ( `@transition(field='state'...)` ) but got an error :( 

AttributeError: 'str' object has no attribute 'change_state'
