### ISSUE TITLE
HOW TO TEST ConcurrentTransitionMixin AND ConcurrentTransitioN ERROR 

### ISSUE THREAD

**Issue by IsmaelMasharo** [viewflow/django-fsm#211]
Im using celery and django-fsm. I've had an invalid transition beetween states. Im now trying to use the ConcurrentTransitionMixin to forbid this kind of behavior but I would like to test and mock a ConcurrentTransition error in order to manage where should I code my try-except blocks.

**Comment by kmmbvnr** [comment]
Probably you can look into django-fsm library tests

https://github.com/viewflow/django-fsm/blob/master/tests/testapp/tests/test_lock_mixin.py#L59
