### ISSUE TITLE
Maintaining this project

### ISSUE THREAD

**Issue by imomaliev** [viewflow/django-fsm#213]
Hi, @kmmbvnr. First of all thanks for such useful project. I see there is already https://github.com/viewflow/django-fsm/issues/193 but django-fsm hasn't been updated for over a year now, and there are multiple issues and PRs pending. I would like to offer myself as collaborator. This project needs 2.x support.

Thanks.

**Comment by kmmbvnr** [comment]
Didn't django-fsm works under Django 2.0 in it's current state?

**Comment by imomaliev** [comment]
@kmmbvnr It works yes, but tests for example fail https://github.com/viewflow/django-fsm/pull/196, and so I can't be sure that there is no issues or quirks that we don't see in basic usage. Plus I think this issue https://github.com/viewflow/django-fsm/issues/209 should be addressed

**Comment by kmmbvnr** [comment]
#209 probably just misuse field reference.

Yeah, probably django-fsm need some improvements, but there is no rush with it.

**Comment by imomaliev** [comment]
@kmmbvnr What do you mean no rush?) How can I be sure to use this project in mine with django 2.1 if it isn't officially supported and may cause some unknown errors related to version mismatch?
