### ISSUE TITLE
Add project to Code Shelter

### ISSUE THREAD

**Issue by skorokithakis** [viewflow/django-fsm#215]
Maintenance on this project seems to have slowed down a bit. If you need some help, please consider adding the project to [Code Shelter](https://www.codeshelter.co/) so volunteers can help maintain it.

Thanks!

**Comment by kmmbvnr** [comment]
On a small and trivial project ts like django-fsm, usual volunteer  "help" requires more efforts and time for improvements than just do the things.

**Comment by kmmbvnr** [comment]
And generally django-fsm looks complete. There is nothing to add, and everything works like expected.

If someone would like to go through the tickets and write answers on user questions + no permission from my side required
