### ISSUE TITLE
Validate source and target states against model "choices"

### ISSUE THREAD

**Issue by pakal** [viewflow/django-fsm#217]
(minor feature request)
It seems that one can declare transitions that arrive to states that are not values listed in FSMField "choices" parameter. 
Always using enums here prevents most of the trouble, but wouldn't it be feasible to ensure, at app loading, that all transitions are valid with regards to this list of choices ?

**Comment by kmmbvnr** [comment]
implemented in viewflow.fsm - https://docs.viewflow.io/fsm/index.html
