### ISSUE TITLE
Magic source '+' undocumented

### ISSUE THREAD

**Issue by moseb** [viewflow/django-fsm#219]
I found a magic source `+` at 
https://github.com/viewflow/django-fsm/blob/957e1d8535f1e8f31cd6f971f4ec6704eb1f2d9a/django_fsm/__init__.py#L166-L179
It seems undocumented, unless I missed it. It would be cool to have a sentence or two about it somewhere.

Thanks!

**Comment by kmmbvnr** [comment]
Yeah, indeed. That documentation needs implement. PR are welcome.

Currently i'm hardly working on Django-fsm 3.0 combined with viewflow 2.0 with new docs site.
