### ISSUE TITLE
FSMKeyField does not prevent direct state field modification when protected=True

### ISSUE THREAD

**Issue by chrisnghs** [viewflow/django-fsm#220]
I have a FSMKeyField set with protected=True, however it does not raise AttributeError when the field is edited directly. 

```
class DbState(models.Model): 
    id = models.CharField(primary_key=True, max_length=50)
    label = models.CharField(max_length=255)

    def __unicode__(self):
          return self.label


class BlogPost(models.Model):
     state = FSMKeyField(DbState, default='new', on_delete=models.CASCADE, **protected=True**)
```

```
model = BlogPost()
model.state = 'invalid' # doesnt raise AttributeError
```

**Comment by chrisnghs** [comment]
It seems that under the class  FSMFieldDescriptor’s __set__ function, instance.__dict__ references the field name with a prefix “_id” when it’s a foreign key. That’s why it didn’t get through to raise the AttributeError

**Comment by yekibud** [comment]
@chrisnghs were you able to get this working?   Do you have a patch?

@kmmbvnr I think `protected=True` is a pretty valuable feature for maintaining state/transition data integrity.  Would be nice to get this fixed.  I've only been POCing the project, but if I wind up using it in production I'll look into it myself.

**Comment by chrisnghs** [comment]
> @chrisnghs were you able to get this working? Do you have a patch?
> 
> @kmmbvnr I think `protected=True` is a pretty valuable feature for maintaining state/transition data integrity. Would be nice to get this fixed. I've only been POCing the project, but if I wind up using it in production I'll look into it myself.

@yekibud i haven't yet actually, cause there weren't much instances that we are editing directly on the field itself

**Comment by kmmbvnr** [comment]
FSMKeyField is actually newer works properly. Closing this since not enough resource to fix
