### ISSUE TITLE
support for python 3.8

### ISSUE THREAD

**Issue by domdinicola** [viewflow/django-fsm#222]

**Comment by MDziwny** [comment]
I'm maintaining a fork of this project, it is tested against all the current versions of Python and django (including the future django 3.0). I'm willing to create a merge request into the main project but last time I did so, the maintainer didn't have time to check it.

https://github.com/MDziwny/django-fsm

And it's published on pypi under the name django-fsa (but the code namespace is the same than in djang-fsm, so you can use it without changing a line of code)

**Comment by domdinicola** [comment]
good to know! thanks
