### ISSUE TITLE
`@transition(on_error='state')` not working

### ISSUE THREAD

**Issue by beaugunderson** [viewflow/django-fsm#231]
Apologies for lack of a repro; we just saw this in production.

We have a model method that species an `on_error` state but an exception was raised in the model method and the state was not set appropriately (the exception bubbled all the way up).

I believe this used to work, so the breakage my have occurred when we upgraded Django to 2.2.10 or Python to 3.8 recently.

**Comment by beaugunderson** [comment]
I simplified our usage to:

```python
    @transition(field=status, source='*', target=STATE_CHARGED, on_error=STATE_FAILED)
    def charge(self):
        raise Exception('Should be handled but is not!')
```

When run:

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/app/testing.py in <module>
---> 46 transaction_charge.charge()

/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py in _change_state(instance, *args, **kwargs)
    513         @wraps(func)
    514         def _change_state(instance, *args, **kwargs):
--> 515             return fsm_meta.field.change_state(instance, func, *args, **kwargs)
    516
    517         if not wrapper_installed:

/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py in change_state(self, instance, method, *args, **kwargs)
    319
    320         try:
--> 321             result = method(instance, *args, **kwargs)
    322             if next_state is not None:
    323                 if hasattr(next_state, 'get_state'):

/app/quality_and_revenue/models/transaction.py in charge(self)
    167         print(amount)
    168
--> 169         raise Exception('Should be handled but is not!')

Exception: Should be handled but is not!
```

**Comment by beaugunderson** [comment]
🤦‍♂ after reading the code I see that the exception is re-raised after the state is handle by the `on_error` handler. I verified that in my simple repro here the state is changed correctly.

I'm curious what pattern should be used for doing some error-handling/cleanup within a transition method? In this case we're calling out to Stripe and want to store the returned error. My current plan is to catch the error from Stripe, save the error, and then re-raise to allow the transition handler to change the status.

**Comment by kmmbvnr** [comment]
>> raise Exception('Should be handled but is not!')

By design django-fsm reraised exceptions, elsewhere exception info would be lost

The next version of django-fsm - the `viewflow.fsm` package allows to call a transitino method inside other, so the errors could be catched as the specific transition method

https://docs-next.viewflow.io/fsm/options.html#target

```python
@stage.transition(source=Stage.NEW, target=Stage.IN_PROCESS)
def pay(self):
    try:
        self.perform_payment()
    except:
        self.error()
````
