### ISSUE TITLE
Comparison with python transitions package

### ISSUE THREAD

**Issue by somghosh** [viewflow/django-fsm#235]
I wanted to know the pros and cons of django-fsm vs  `transitions` , https://github.com/pytransitions/transitions

Although this is pure python they have good faq on how to use it in Django.

https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb

Any info on the relative plus/minus of the two packages and which one is suitable where, if any such use cases favour one over another inside the business logic/transitions use cases will be appreciated

**Comment by kmmbvnr** [comment]
Seems it follows completly different approach to describe state machine

`viewflow.fsm` former django-fsm package tries to be python-native, where as transitions package provides  java-like api
