### ISSUE TITLE
State Diagrams in Mermaid Markdown

### ISSUE THREAD

**Issue by alysivji** [viewflow/django-fsm#241]
Thank you for creating this library! I use it all the time and love the API.

I took a couple of hours and wrote up a function that generates `django-fsm` State Diagrams in [Mermaid Markdown](https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/stateDiagram.html) syntax.

Is there any interest in having `django-fsm` support another visualization format? I can clean my code and make a PR.

Attached is a diagram for one of the models in `testapp`:

<img src="https://user-images.githubusercontent.com/4369343/93007543-8d3bdc80-f52f-11ea-8376-7655f84916a8.png" width=350 />

**Comment by peterfarrell** [comment]
@alysivji Would you share a link to the code?

**Comment by alysivji** [comment]
https://gist.github.com/alysivji/0475531d2703373c024a60a63b8a2db6

Let me know if you need me to clean this up and make a PR. Would love to contribute to this project. I use it all the time.

**Comment by peterfarrell** [comment]
@alysivji You could consider releasing this as `django-fsm-graph-transitions-mermaid` package on PyPi.

**Comment by kmmbvnr** [comment]
Closing since it's not enough resource on this
