### ISSUE TITLE
Question: Identify which condition failed

### ISSUE THREAD

**Issue by dnievas04** [viewflow/django-fsm#251]
When working with conditions between transitions, Is it possible to identify which condition failed? It would be nice to know what went wrong.

Thanks!

**Comment by kmmbvnr** [comment]
Implemented in the viewflow.fsm module - https://github.com/viewflow/viewflow/blob/v2/tests/fsm/test_fsm__conditions.py#L26

**Comment by ds-clearago** [comment]
New Link
> Implemented in the viewflow.fsm module - https://github.com/viewflow/viewflow/blob/v2/tests/fsm/test_fsm__conditions.py#L26
