### ISSUE TITLE
FSMKeyField and nested serialization

### ISSUE THREAD

**Issue by MartinSchmidt123** [viewflow/django-fsm#257]
Hi, I am using django-fsm with djangorestframework. 
As an example, I have the following models
```
class TaskStatus(models.Model):
    value = models.CharField(max_length=50, primary_key=True)
    sorting = models.IntegerField()


class Task(models.Model):
    name = models.CharField(max_length=50)
    fk_status = models.ForeignKey(TaskStatus, default='draft', on_delete=models.CASCADE,related_name='+')
    fsm_status = FSMKeyField(TaskStatus, default='draft', on_delete=models.CASCADE,related_name='+')
```

Converting a ForeignKey `fk_status` to a FSMKeyField `fsm_status` breaks the nested serialization. 
While the following works for a ForeignKey:
```
class TaskStatusSerializer(serializers.ModelSerializer):
    class Meta:
        model = TaskStatus
        fields = ['value', 'sorting']


class GoodTaskSerializer(serializers.ModelSerializer):
    fk_status = TaskStatusSerializer(read_only=True)

    class Meta:
        model = Task
        fields = ['fk_status', 'name', ]
```
using the serializer
```
class BadTaskSerializer(serializers.ModelSerializer):
    fsm_status = TaskStatusSerializer(read_only=True)

    class Meta:
        model = Task
        fields = ['fsm_status', 'name', ]
```
gives the error

> Got AttributeError when attempting to get a value for field `value` on serializer `TaskStatusSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'value'.

The reason seems to be that django-fsm overrides the `__get__`-method in https://github.com/viewflow/django-fsm/blob/2550746dc038fe1fb8eeb77bf260076590154722/django_fsm/__init__.py#L231

I am not sure whether there is an solution for the nested serialization issue. But we should at least document the trade-offs/drawbacks of using an FSMKeyField.

A full example is available at https://github.com/MartinSchmidt123/django_tasks. You can clone the repo and run
> docker-compose up

and open `http://127.0.0.1:8000/`

---

On a side note:
It is also not possible to assign a TaskStatus object to the fsm_status  field, e.g. you cannot do
```
    draft, _ = TaskStatus.objects.update_or_create(value='draft', defaults={'sorting': 1})
    Task.objects.update_or_create(name='task 1',fk_status=draft,fsm_status=draft)
```
but have to write
```
    Task.objects.update_or_create(name='task 1',fk_status=draft,fsm_status='draft')
```
(Except in cases where you define  `__str__` to return the fsm_status value)

**Comment by kmmbvnr** [comment]
I'm not sure what could goes wrong in the case of rest-framework plus nested serialization, but I've implemented better approach to the fsm modeling, that not bound to the django models.



https://docs-next.viewflow.io/fsm/index.html
