### ISSUE TITLE
ManyToMany relation not saved inside a @transition method

### ISSUE THREAD

**Issue by jej** [viewflow/django-fsm#259]
I struggle with a strange problem... I use fsm with pleasure since few days, just to change a state field and use action buttons in admin to switch the state. On one transition I do some updates in the db, by calling a `self.my_update()` on the model inside the @transition method. No problem.

Today I added a ManyToMany field on that model. When I call the method from outside fsm world, it works well. The m2m relation is created/updated as expected. But when the same method is called inside the @transition, the model fields are saved but not the m2m relations. I tried a lot of workaround (saving intensively...) but nothing helped. Mayby something related to transaction.
Any idea what could be the problem? Thx

edit: it seems related to django-fsm-admin, because a call to the transition method works as expected. So I move there...

**Comment by kmmbvnr** [comment]
django-fsm 2,0 designed in assumption that `.save` method would be called outside of transition method

I've placed the next versino of django.fsm into the viewflow.fsm package. New approach separates models and fsm definitions, to allow explicit save(...) and other parameters changes.

https://docs-next.viewflow.io/fsm/models.html
