### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [viewflow/django-fsm#267]
We are looking forward to using `django-fsm` with Django 3.2 on [edX](https://github.com/edx).

Required [commit](https://github.com/viewflow/django-fsm/commit/df83da59422e9407d64d3dda6ecf30d345650485) is already merged into the master branch.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by kmmbvnr** [comment]
If you don't use get_available_FIELD_transitions method, you can stay on the latest available django-fsm version on pypi

If you need, new version of fsm, you could upgrade to django-viewflow==2.0.0a0

https://docs-next.viewflow.io/fsm/index.html

**Comment by ticosax** [comment]
@kmmbvnr What are your plans regarding django-fsm ?

I understand django-fsm is more or less deprecated in favor of django-viewflow, is that correct ?
In that case, given there is still some users willing to continue to use django-fsm and to maintain it, have you given some thought on how to `transition` (pun intended :smile: ) the project, so it stays relevant in the future ?

Do you plan on inviting other maintainers ?
Or Maybe to transfer the project to https://github.com/jazzband ?

**Comment by kmmbvnr** [comment]
I'm just moving all my projects into single package to simplify maintenance and new features development

`viewflow.fsm` depricates django-fsm like React 0.65 with hooks deprecates React 0.16 with classes.

`viewflow.fsm` separates Model and Fsm classes, that removes many hacks and bugs workarounds, to get FSM and django ORM work together. Simple [Model and FSM class integration](https://docs-next.viewflow.io/fsm/models.html) depricates 3d party packages like django-fsm-log and django-fsm-admin, django-fsm-rest

**Comment by GitRon** [comment]
We are just evaluating to use `django-fsm` in a quite large project. Any recommendations about that?

**Comment by kmmbvnr** [comment]
@GitRon You need to switch to [`viewflow.fsm`](https://docs-next.viewflow.io/fsm/index.html) It's the django-fsm 3.0, that incorporates all my previous experience of django-fsm package development.

Several issues in this repository can't be fixed in django-fsm 2.0 (ex refresh_from_db along with protected=True) but they didn't even happen in the `viewflow.fsm`

**Comment by GitRon** [comment]
@kmmbvnr Thanks for the hint! The docs still have larger blank spaces... this worries me a little for using it in production. Am I to worry about that? 😅 What would be the link to the pypi package? The quick start section is still empty, right? 😄

**Comment by kmmbvnr** [comment]
@GitRon fsm part is complete. The spaces are reffered to other parts of package. You could install the latest version with `pip install django-viewflow==2.0.0a0`
