### ISSUE TITLE
How to handle `can_proceed(transition) == False`

### ISSUE THREAD

**Issue by FractalWire** [viewflow/django-fsm#268]
Hi,

We currently use transition in what seems to be the expected pattern, e.g.:

```python 
if can_proceed(my.transition):
    my.transition()
else:
    raise TransitionCantProceed
```

The issue with this pattern is that we do not have details about why the transition can't proceed.

It could be because of a bad source state, a conditions == False or a missing paermission.

As far as I can see, there is no obvious way to get the reason why it can't proceed in the else case.
One way would be to create a custom method to check every possible failure. For exemple:

```python
def cant_proceed_transition_reason(self, user):
    if not self.check_some_condition():
        return "some_condition is not met"
    if not user.check_some_permission():
        return "some_permission is not met"
    if not self.state in EXPECTED_SOURCE_TARGET:
        return f"{self.state} not a valid source target for transition"
```

I find that ugly. Is there a better way ?

**Comment by kmmbvnr** [comment]
See #251 and new module `viewflow.fsm` - https://github.com/viewflow/viewflow/blob/v2/tests/fsm/test_fsm__conditions.py#L26
