### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by adamchainz** [viewflow/django-fsm#280]
The GitHub repo shows the tagged releases on GitHub, and displays the most recent version as 2.6.1, April 2019:

<img width="240" alt="Screenshot 2022-03-21 at 13 01 14" src="https://user-images.githubusercontent.com/857609/159266193-ec62ccad-0375-490f-83bf-2e49461d1bcb.png">

So at first glance, I thought this package was not being maintained.

You could either add tags and GitHub releases for 2.7.0+, or use GitHub's repo page settings to stop showing the releases section.

**Comment by kmmbvnr** [comment]
I've just added the 2.8.0. But it robably would be the latest one. The project has been moved to viewflow.fsm package

**Comment by adamchainz** [comment]
Thanks. If you are deprecating this package, could you add a note at the top of its README explaining the situation?
