### ISSUE TITLE
Update package to support Django 4

### ISSUE THREAD

**Issue by danigayosog** [viewflow/django-fsm#284]
Support for Django 4 is made in the commit https://github.com/viewflow/django-fsm/commit/12a1935251255bfde1e58060333328635f50db1e and it's already integrated in master branch. 

Could you release a new version with this fix to PyPi?

**Comment by enflo** [comment]
Could you release a new version with this fix to PyPi and extend support to django 4?

**Comment by maerteijn** [comment]
@mmbvnr Is this something you could do and do you need any help with it?

**Comment by kmmbvnr** [comment]
There was a little issue, with some complicated use-case, the proper way would be not use django-fsm in that way 

The fix released.
