### ISSUE TITLE
No active CI for the builds

### ISSUE THREAD

**Issue by mpasternak** [viewflow/django-fsm#285]
Is there a maintainer around? @dfg-98 , maybe? 

Do you need help with django-fsm? 

I'm asking, because there are no GitHub Action builds and I'm willing to help you, as long as the maintainer is around, willing to merge.

**Comment by maerteijn** [comment]
@mmbvnr I would also be willing to help with this, any chance you would review / merge it when @mpasternak or me would take the time to set it up?

**Comment by mpasternak** [comment]
@maerteijn if you’re interested maybe we could talk @jazzband into taking over the repository and we could cooperate on the project there.

**Comment by maerteijn** [comment]
@mpasternak I think that would be great, but first one one the maintainers has to give us a sign of life and decide if that would be a desirable road to follow. (django-fsm-log is already a jazzband project so it would make sense IMO)

**Comment by kmmbvnr** [comment]
django-fsm project is became part of viewflow - https://docs-next.viewflow.io/fsm/index.html

This repository would be archived soon

**Comment by mpasternak** [comment]
@kmmbvnr +1 on what @ticosax wrote. Would you be willing to accept patches for this repo or to transfer ownership? If not, this is another few forks more... and possibly duplicated effort.

Or, should we just ditch django-fsm and move to viewflow?
