### ISSUE TITLE
Allowing incorrect state transitions

### ISSUE THREAD

**Issue by pbalakri** [viewflow/django-fsm#295]
Hello,
I'm using fsm for my project. Code for the class provided below. The transitions are not firing properly. My understanding is that transitions that a re not explicitly mentioned will be considered as an error. But this is not happening for me. I'm able to traverse from any state to any state. Secondly, I'm also able to traverse to an illegal state say "asdf". 

Please help!

`
class Offer(models.Model):
    id = models.AutoField(primary_key=True)
    opportunity = models.ForeignKey(Opportunity, on_delete=models.RESTRICT)
    contact = models.ForeignKey(Contact, on_delete=models.RESTRICT)

    status = FSMField(
        default="pending_deposit")

    @transition(field=status, source="pending_deposit", target="pending_kyc")
    def pending_kyc(self):
        return ("pending_kyc")

    @transition(field=status, source="pending_kyc", target="pending_spa")
    def pending_spa(self):
        pass

    @transition(field=status, source="pending_spa", target="pending_minimum_payment")
    def pending_minimum_payment(self):
        pass

    @transition(field=status, source="pending_minimum_payment", target="pending_dld_payment")
    def pending_dld_payment(self):
        pass

    @transition(field=status, source="pending_dld_payment", target="sales_offer_closed")
    def sales_offer_closed(self):
        pass

    @transition(field=status, source="sales_offer_closed", target="commission_paid")
    def commission_paid(self):
        pass

    @transition(field=status, source=["pending_deposit", "pending_kyc", "pending_spa", "pending_minimum_payment"], target="rejected")
    def sales_offer_rejected(self):
        pass
`

**Comment by pbalakri** [comment]
To clarify I'm change the status value from django_admin

**Comment by samucancld** [comment]
> To clarify I'm change the status value from django_admin

You're changing the field value directly then, not using the transitions provided by the library. You could try with `django-fsm-admin` or write your own logic

**Comment by kmmbvnr** [comment]
To get admin support you could use new viewflow.fsm that provide admin support via custom buttons for transitions - https://docs.viewflow.io/fsm/admin.html
