### ISSUE TITLE
Question: How to deal with async errors of side effects

### ISSUE THREAD

**Issue by ds-clearago** [viewflow/django-fsm#299]
Hi,
I've tried to find an answer to this in the docs and in issues or PRs but haven't found anything exact except https://github.com/viewflow/django-fsm/issues/231 which is only partially similar to the topic:

Imagine the following FSM:
`Order Open`
 ----send-email-------> `Purchase Order Sent to Supplier`
 ----button-clicked----> `PO confirmed by supplier`

To send out transactional emails we're using the ESP [Sparkpost](https://developers.sparkpost.com/api/). 
We want to make sure that the status only moves, not only when we've sent our API call to the ESP, but when the ESP actually managed to send the mail out (otherwise our state machine will be showing that the email has been sent, even though we only tried to get it out unsuccessfully).
If we get an [immediate error](https://developers.sparkpost.com/api/#header-error-table) during the api call (e.g. for a malformed request), then the transition will fail with an error – so that's fine.

But Sparkpost can be queried for and also sends out [webhooks](https://developers.sparkpost.com/api/webhooks/#header-webhook-event-types) for the event `delivery` (_Remote MTA acknowledged receipt of a message_). 

In order to do handle this, we currently have the following process (currently unfortunately implemented rather manually w/o django-fsm):

`Order Open` 
----**send-api-call**-----> `Purchase Order Sending` --------**delivery-event**-------->`Purchase Order Sent to Supplier` 
----button-clicked----> `PO confirmed by Supplier`

There is no way how I can reliably handle the async response for a successful transition and therefore avoid the transitory "sending" status with django-fsm, right?

Thanks a lot for any guidance!
Best,
Dennis

PS: In the abovementioned issue, 
[kmmbvnr](https://github.com/kmmbvnr) commented [on Dec 9, 2020](https://github.com/viewflow/django-fsm/issues/231#issuecomment-741746105)
> The next version of django-fsm - the `viewflow.fsm` package allows to call a transitino method inside other, so the errors could be catched as the specific transition method
> https://docs-next.viewflow.io/fsm/options.html#target

It seems to me that the next version of django-fsm is still going to be the django-fsm package itself and not directly related (nor replaced) by [viewflow](https://github.com/viewflow/viewflow), right? Especially since the above link is broken too?

**Comment by kmmbvnr** [comment]
You should not avoid sending status.

The documentation released at https://docs.viewflow.io/fsm/options.html#target
