### ISSUE TITLE
TypeError: Error when calling the metaclass bases contribute_to_class() got an unexpected keyword argument 'virtual_only'

### ISSUE THREAD

**Issue by crolfe** [viewflow/django-fsm#30]
If I use the latest version from pip (2.0.1) with Django 1.5.5, I encounter a TypeError when I try to define a field like this:

`state = FSMField(default='new')`

I also tried using the FSMIntegerField and I get the same error.  I tried installing 1.6 from pip exactly as above (although the imports are different) and the above works.

Let me know if there's something I'm doing wrong, or there's anything else I can provide to help troubleshoot.

**Comment by hawk5555** [comment]
when I  run python manage.py syncdb, TypeError: transition() got an unexpected keyword argument 'custom'.
i run pip list ,this results is:
Django           2.2.3
django-fsm       2.0.1
django-fsm-admin 1.2.4   g:\github\django-fsm-admin
pip              19.2.1
pytz             2019.1
setuptools       41.0.1
sqlparse         0.3.0
wheel            0.33.4
what is wrong?

**Comment by hawk5555** [comment]
when I run python manage.py syncdb, TypeError: transition() got an unexpected keyword argument 'custom'.
i run 
`pip list` 
this results are:
Django 2.2.3
django-fsm 2.0.1
django-fsm-admin 1.2.4 g:\github\django-fsm-admin
pip 19.2.1
pytz 2019.1
setuptools 41.0.1
sqlparse 0.3.0
wheel 0.33.4

what is wrong?

**Comment by hawk5555** [comment]
when I run `python manage.py syncdb,` 
debug: `contribute_to_class
    super(FSMFieldMixin, self).contribute_to_class(cls, name, virtual_only=virtual_only)
TypeError: contribute_to_class() got an unexpected keyword argument 'virtual_only'`
i run pip list ,this results are:
`Django           2.2.3
django-fsm       2.0.1
django-fsm-admin 1.2.4   g:\github\django-fsm-admin
pip              19.2.1
pytz             2019.1
setuptools       41.0.1
sqlparse         0.3.0
wheel            0.33.4`
