### ISSUE TITLE
set state fields to readonly in django admin when protected=True

### ISSUE THREAD

**Issue by puterleat** [viewflow/django-fsm#5]
Would it make more sense to set state fields to readonly in django admin when protected=True?

**Comment by kmmbvnr** [comment]
Looks possible today
![Uploading django options.py at master · django django.png…]()

**Comment by treyd** [comment]
You can do this in your ModelAdmin by adding the following:

```
    readonly_fields = ['state']
```
Where `'state'` is the name of your FSMField in your model.  That makes it not render as a drop-down in the admin edit instance view (in 1.11)

**Comment by kmmbvnr** [comment]
The problem goes away from the next version of the package.

`viewflow.fsm` separates FSM flow and Django model. Flow class state field prevents modifications, and the django model admin could set state field as read only if required.

https://docs-next.viewflow.io/fsm/models.html

Thanks everyone for the participating in the issue.
